; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35211.0 

	TITLE	D:\src\toy-computer\dasm\fib.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	_fib
PUBLIC	_main
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
_DATA	SEGMENT
$SG10019 DB	'%d ', 00H
$SG10023 DB	'%d', 0aH, 00H
_DATA	ENDS
; Function compile flags: /Odtp
; File D:\src\toy-computer\dasm\fib.c
_TEXT	SEGMENT
_x$ = -4						; size = 4
_main	PROC

; 17   : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 18   :     int x = fib(20);

	push	20					; 00000014H
	call	_fib
	add	esp, 4
	mov	DWORD PTR _x$[ebp], eax

; 19   :     printf("%d\n", x);

	mov	eax, DWORD PTR _x$[ebp]
	push	eax
	push	OFFSET $SG10023
	call	_printf
	add	esp, 8

; 20   :     return 0;

	xor	eax, eax

; 21   : }

	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File D:\src\toy-computer\dasm\fib.c
_TEXT	SEGMENT
_b$ = -8						; size = 4
_a$ = -4						; size = 4
_n$ = 8							; size = 4
_fib	PROC

; 4    : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8

; 5    :     if(n <= 2)

	cmp	DWORD PTR _n$[ebp], 2
	jg	SHORT $LN2@fib

; 6    :         return 1;

	mov	eax, 1
	jmp	SHORT $LN1@fib
$LN2@fib:

; 7    : 
; 8    :     int a = fib(n - 1);

	mov	eax, DWORD PTR _n$[ebp]
	sub	eax, 1
	push	eax
	call	_fib
	add	esp, 4
	mov	DWORD PTR _a$[ebp], eax

; 9    :     int b = fib(n - 2);

	mov	ecx, DWORD PTR _n$[ebp]
	sub	ecx, 2
	push	ecx
	call	_fib
	add	esp, 4
	mov	DWORD PTR _b$[ebp], eax

; 10   : 
; 11   :     printf("%d ", a+b);

	mov	edx, DWORD PTR _a$[ebp]
	add	edx, DWORD PTR _b$[ebp]
	push	edx
	push	OFFSET $SG10019
	call	_printf
	add	esp, 8

; 12   : 
; 13   :     return a + b;

	mov	eax, DWORD PTR _a$[ebp]
	add	eax, DWORD PTR _b$[ebp]
$LN1@fib:

; 14   : }

	mov	esp, ebp
	pop	ebp
	ret	0
_fib	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\stdio.h
;	COMDAT _printf
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT

; 956  :     {

	push	ebp
	mov	ebp, esp
	sub	esp, 8

; 957  :         int _Result;
; 958  :         va_list _ArgList;
; 959  :         __crt_va_start(_ArgList, _Format);

	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax

; 960  :         _Result = _vfprintf_l(stdout, _Format, NULL, _ArgList);

	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	1
	call	___acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfprintf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax

; 961  :         __crt_va_end(_ArgList);

	mov	DWORD PTR __ArgList$[ebp], 0

; 962  :         return _Result;

	mov	eax, DWORD PTR __Result$[ebp]

; 963  :     }

	mov	esp, ebp
	pop	ebp
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\stdio.h
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT

; 644  :     {

	push	ebp
	mov	ebp, esp

; 645  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H

; 646  :     }

	pop	ebp
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_stdio_config.h
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT

; 90   :     {

	push	ebp
	mov	ebp, esp

; 91   :         static unsigned __int64 _OptionsStorage;
; 92   :         return &_OptionsStorage;

	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@9 ; `__local_stdio_printf_options'::`2'::_OptionsStorage

; 93   :     }

	pop	ebp
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
