//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from toy_asm.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class toy_asmParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, T__40=41, Comment=42, INT=43, Label=44, STR=45, WS=46;
	public const int
		RULE_program = 0, RULE_opWithLabel = 1, RULE_opLabel = 2, RULE_op = 3, 
		RULE_num = 4, RULE_reg = 5, RULE_offset = 6, RULE_mem = 7, RULE_str = 8, 
		RULE_move = 9, RULE_add = 10, RULE_sub = 11, RULE_mul = 12, RULE_div = 13, 
		RULE_cmp = 14, RULE_jump = 15, RULE_call = 16, RULE_ret = 17, RULE_push_op = 18, 
		RULE_pop_op = 19, RULE_input = 20, RULE_print = 21, RULE_rand = 22, RULE_dump = 23, 
		RULE_pause = 24, RULE_halt = 25, RULE_nop = 26;
	public static readonly string[] ruleNames = {
		"program", "opWithLabel", "opLabel", "op", "num", "reg", "offset", "mem", 
		"str", "move", "add", "sub", "mul", "div", "cmp", "jump", "call", "ret", 
		"push_op", "pop_op", "input", "print", "rand", "dump", "pause", "halt", 
		"nop"
	};

	private static readonly string[] _LiteralNames = {
		null, "':'", "'+'", "'-'", "'ax'", "'bx'", "'cx'", "'dx'", "'bp'", "'sp'", 
		"'['", "']'", "'mov'", "','", "'add'", "'sub'", "'mul'", "'div'", "'cmp'", 
		"'jmp'", "'je'", "'jne'", "'jg'", "'jge'", "'jl'", "'jle'", "'call'", 
		"'ret'", "'push'", "'pushf'", "'pusha'", "'pop'", "'popf'", "'popa'", 
		"'input'", "'print'", "'println'", "'rand'", "'dump'", "'pause'", "'halt'", 
		"'nop'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, "Comment", "INT", "Label", "STR", 
		"WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "toy_asm.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static toy_asmParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public toy_asmParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public toy_asmParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comment() { return GetTokens(toy_asmParser.Comment); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comment(int i) {
			return GetToken(toy_asmParser.Comment, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpWithLabelContext[] opWithLabel() {
			return GetRuleContexts<OpWithLabelContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpWithLabelContext opWithLabel(int i) {
			return GetRuleContext<OpWithLabelContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 56;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				State = 56;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case Comment:
					{
					State = 54;
					Match(Comment);
					}
					break;
				case T__11:
				case T__13:
				case T__14:
				case T__15:
				case T__16:
				case T__17:
				case T__18:
				case T__19:
				case T__20:
				case T__21:
				case T__22:
				case T__23:
				case T__24:
				case T__25:
				case T__26:
				case T__27:
				case T__28:
				case T__29:
				case T__30:
				case T__31:
				case T__32:
				case T__33:
				case T__34:
				case T__35:
				case T__36:
				case T__37:
				case T__38:
				case T__39:
				case T__40:
				case Label:
					{
					State = 55;
					opWithLabel();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 58;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 26388279054336L) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OpWithLabelContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OpContext op() {
			return GetRuleContext<OpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpLabelContext opLabel() {
			return GetRuleContext<OpLabelContext>(0);
		}
		public OpWithLabelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_opWithLabel; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterOpWithLabel(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitOpWithLabel(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOpWithLabel(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OpWithLabelContext opWithLabel() {
		OpWithLabelContext _localctx = new OpWithLabelContext(Context, State);
		EnterRule(_localctx, 2, RULE_opWithLabel);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 61;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Label) {
				{
				State = 60;
				opLabel();
				}
			}

			State = 63;
			op();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OpLabelContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Label() { return GetToken(toy_asmParser.Label, 0); }
		public OpLabelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_opLabel; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterOpLabel(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitOpLabel(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOpLabel(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OpLabelContext opLabel() {
		OpLabelContext _localctx = new OpLabelContext(Context, State);
		EnterRule(_localctx, 4, RULE_opLabel);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 65;
			Match(Label);
			State = 66;
			Match(T__0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MoveContext move() {
			return GetRuleContext<MoveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AddContext add() {
			return GetRuleContext<AddContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SubContext sub() {
			return GetRuleContext<SubContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MulContext mul() {
			return GetRuleContext<MulContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DivContext div() {
			return GetRuleContext<DivContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CmpContext cmp() {
			return GetRuleContext<CmpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public JumpContext jump() {
			return GetRuleContext<JumpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CallContext call() {
			return GetRuleContext<CallContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RetContext ret() {
			return GetRuleContext<RetContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Push_opContext push_op() {
			return GetRuleContext<Push_opContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pop_opContext pop_op() {
			return GetRuleContext<Pop_opContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InputContext input() {
			return GetRuleContext<InputContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrintContext print() {
			return GetRuleContext<PrintContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RandContext rand() {
			return GetRuleContext<RandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DumpContext dump() {
			return GetRuleContext<DumpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PauseContext pause() {
			return GetRuleContext<PauseContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public HaltContext halt() {
			return GetRuleContext<HaltContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NopContext nop() {
			return GetRuleContext<NopContext>(0);
		}
		public OpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_op; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OpContext op() {
		OpContext _localctx = new OpContext(Context, State);
		EnterRule(_localctx, 6, RULE_op);
		try {
			State = 86;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__11:
				EnterOuterAlt(_localctx, 1);
				{
				State = 68;
				move();
				}
				break;
			case T__13:
				EnterOuterAlt(_localctx, 2);
				{
				State = 69;
				add();
				}
				break;
			case T__14:
				EnterOuterAlt(_localctx, 3);
				{
				State = 70;
				sub();
				}
				break;
			case T__15:
				EnterOuterAlt(_localctx, 4);
				{
				State = 71;
				mul();
				}
				break;
			case T__16:
				EnterOuterAlt(_localctx, 5);
				{
				State = 72;
				div();
				}
				break;
			case T__17:
				EnterOuterAlt(_localctx, 6);
				{
				State = 73;
				cmp();
				}
				break;
			case T__18:
			case T__19:
			case T__20:
			case T__21:
			case T__22:
			case T__23:
			case T__24:
				EnterOuterAlt(_localctx, 7);
				{
				State = 74;
				jump();
				}
				break;
			case T__25:
				EnterOuterAlt(_localctx, 8);
				{
				State = 75;
				call();
				}
				break;
			case T__26:
				EnterOuterAlt(_localctx, 9);
				{
				State = 76;
				ret();
				}
				break;
			case T__27:
			case T__28:
			case T__29:
				EnterOuterAlt(_localctx, 10);
				{
				State = 77;
				push_op();
				}
				break;
			case T__30:
			case T__31:
			case T__32:
				EnterOuterAlt(_localctx, 11);
				{
				State = 78;
				pop_op();
				}
				break;
			case T__33:
				EnterOuterAlt(_localctx, 12);
				{
				State = 79;
				input();
				}
				break;
			case T__34:
			case T__35:
				EnterOuterAlt(_localctx, 13);
				{
				State = 80;
				print();
				}
				break;
			case T__36:
				EnterOuterAlt(_localctx, 14);
				{
				State = 81;
				rand();
				}
				break;
			case T__37:
				EnterOuterAlt(_localctx, 15);
				{
				State = 82;
				dump();
				}
				break;
			case T__38:
				EnterOuterAlt(_localctx, 16);
				{
				State = 83;
				pause();
				}
				break;
			case T__39:
				EnterOuterAlt(_localctx, 17);
				{
				State = 84;
				halt();
				}
				break;
			case T__40:
				EnterOuterAlt(_localctx, 18);
				{
				State = 85;
				nop();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(toy_asmParser.INT, 0); }
		public NumContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_num; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterNum(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitNum(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNum(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumContext num() {
		NumContext _localctx = new NumContext(Context, State);
		EnterRule(_localctx, 8, RULE_num);
		int _la;
		try {
			State = 94;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__1:
			case INT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 89;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__1) {
					{
					State = 88;
					Match(T__1);
					}
				}

				State = 91;
				Match(INT);
				}
				break;
			case T__2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 92;
				Match(T__2);
				State = 93;
				Match(INT);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RegContext : ParserRuleContext {
		public RegContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_reg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterReg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitReg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RegContext reg() {
		RegContext _localctx = new RegContext(Context, State);
		EnterRule(_localctx, 10, RULE_reg);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 1008L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OffsetContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(toy_asmParser.INT, 0); }
		public OffsetContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_offset; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterOffset(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitOffset(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOffset(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OffsetContext offset() {
		OffsetContext _localctx = new OffsetContext(Context, State);
		EnterRule(_localctx, 12, RULE_offset);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 98;
			_la = TokenStream.LA(1);
			if ( !(_la==T__1 || _la==T__2) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 99;
			Match(INT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MemContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OffsetContext offset() {
			return GetRuleContext<OffsetContext>(0);
		}
		public MemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mem; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterMem(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitMem(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMem(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MemContext mem() {
		MemContext _localctx = new MemContext(Context, State);
		EnterRule(_localctx, 14, RULE_mem);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 101;
			Match(T__9);
			State = 102;
			reg();
			State = 104;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__1 || _la==T__2) {
				{
				State = 103;
				offset();
				}
			}

			State = 106;
			Match(T__10);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StrContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STR() { return GetToken(toy_asmParser.STR, 0); }
		public StrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_str; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterStr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitStr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StrContext str() {
		StrContext _localctx = new StrContext(Context, State);
		EnterRule(_localctx, 16, RULE_str);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 108;
			Match(STR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MoveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext[] reg() {
			return GetRuleContexts<RegContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg(int i) {
			return GetRuleContext<RegContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public MoveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_move; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterMove(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitMove(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMove(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MoveContext move() {
		MoveContext _localctx = new MoveContext(Context, State);
		EnterRule(_localctx, 18, RULE_move);
		try {
			State = 135;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 110;
				Match(T__11);
				State = 111;
				reg();
				State = 112;
				Match(T__12);
				State = 113;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 115;
				Match(T__11);
				State = 116;
				reg();
				State = 117;
				Match(T__12);
				State = 118;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 120;
				Match(T__11);
				State = 121;
				reg();
				State = 122;
				Match(T__12);
				State = 123;
				mem();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 125;
				Match(T__11);
				State = 126;
				mem();
				State = 127;
				Match(T__12);
				State = 128;
				num();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 130;
				Match(T__11);
				State = 131;
				mem();
				State = 132;
				Match(T__12);
				State = 133;
				reg();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AddContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext[] reg() {
			return GetRuleContexts<RegContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg(int i) {
			return GetRuleContext<RegContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public AddContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_add; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterAdd(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitAdd(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAdd(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AddContext add() {
		AddContext _localctx = new AddContext(Context, State);
		EnterRule(_localctx, 20, RULE_add);
		try {
			State = 152;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 137;
				Match(T__13);
				State = 138;
				reg();
				State = 139;
				Match(T__12);
				State = 140;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 142;
				Match(T__13);
				State = 143;
				reg();
				State = 144;
				Match(T__12);
				State = 145;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 147;
				Match(T__13);
				State = 148;
				reg();
				State = 149;
				Match(T__12);
				State = 150;
				mem();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SubContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext[] reg() {
			return GetRuleContexts<RegContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg(int i) {
			return GetRuleContext<RegContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public SubContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sub; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterSub(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitSub(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSub(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SubContext sub() {
		SubContext _localctx = new SubContext(Context, State);
		EnterRule(_localctx, 22, RULE_sub);
		try {
			State = 169;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 154;
				Match(T__14);
				State = 155;
				reg();
				State = 156;
				Match(T__12);
				State = 157;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 159;
				Match(T__14);
				State = 160;
				reg();
				State = 161;
				Match(T__12);
				State = 162;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 164;
				Match(T__14);
				State = 165;
				reg();
				State = 166;
				Match(T__12);
				State = 167;
				mem();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MulContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public MulContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mul; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterMul(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitMul(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMul(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MulContext mul() {
		MulContext _localctx = new MulContext(Context, State);
		EnterRule(_localctx, 24, RULE_mul);
		try {
			State = 177;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 171;
				Match(T__15);
				State = 172;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 173;
				Match(T__15);
				State = 174;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 175;
				Match(T__15);
				State = 176;
				mem();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DivContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public DivContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_div; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterDiv(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitDiv(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDiv(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DivContext div() {
		DivContext _localctx = new DivContext(Context, State);
		EnterRule(_localctx, 26, RULE_div);
		try {
			State = 185;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 179;
				Match(T__16);
				State = 180;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 181;
				Match(T__16);
				State = 182;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 183;
				Match(T__16);
				State = 184;
				mem();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CmpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext[] reg() {
			return GetRuleContexts<RegContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg(int i) {
			return GetRuleContext<RegContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public CmpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cmp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterCmp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitCmp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCmp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CmpContext cmp() {
		CmpContext _localctx = new CmpContext(Context, State);
		EnterRule(_localctx, 28, RULE_cmp);
		try {
			State = 202;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 187;
				Match(T__17);
				State = 188;
				reg();
				State = 189;
				Match(T__12);
				State = 190;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 192;
				Match(T__17);
				State = 193;
				reg();
				State = 194;
				Match(T__12);
				State = 195;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 197;
				Match(T__17);
				State = 198;
				reg();
				State = 199;
				Match(T__12);
				State = 200;
				mem();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JumpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Label() { return GetToken(toy_asmParser.Label, 0); }
		public JumpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jump; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterJump(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitJump(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJump(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JumpContext jump() {
		JumpContext _localctx = new JumpContext(Context, State);
		EnterRule(_localctx, 30, RULE_jump);
		try {
			State = 218;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__18:
				EnterOuterAlt(_localctx, 1);
				{
				State = 204;
				Match(T__18);
				State = 205;
				Match(Label);
				}
				break;
			case T__19:
				EnterOuterAlt(_localctx, 2);
				{
				State = 206;
				Match(T__19);
				State = 207;
				Match(Label);
				}
				break;
			case T__20:
				EnterOuterAlt(_localctx, 3);
				{
				State = 208;
				Match(T__20);
				State = 209;
				Match(Label);
				}
				break;
			case T__21:
				EnterOuterAlt(_localctx, 4);
				{
				State = 210;
				Match(T__21);
				State = 211;
				Match(Label);
				}
				break;
			case T__22:
				EnterOuterAlt(_localctx, 5);
				{
				State = 212;
				Match(T__22);
				State = 213;
				Match(Label);
				}
				break;
			case T__23:
				EnterOuterAlt(_localctx, 6);
				{
				State = 214;
				Match(T__23);
				State = 215;
				Match(Label);
				}
				break;
			case T__24:
				EnterOuterAlt(_localctx, 7);
				{
				State = 216;
				Match(T__24);
				State = 217;
				Match(Label);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CallContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Label() { return GetToken(toy_asmParser.Label, 0); }
		public CallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_call; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CallContext call() {
		CallContext _localctx = new CallContext(Context, State);
		EnterRule(_localctx, 32, RULE_call);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 220;
			Match(T__25);
			State = 221;
			Match(Label);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RetContext : ParserRuleContext {
		public RetContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ret; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterRet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitRet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRet(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RetContext ret() {
		RetContext _localctx = new RetContext(Context, State);
		EnterRule(_localctx, 34, RULE_ret);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 223;
			Match(T__26);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Push_opContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		public Push_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_push_op; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterPush_op(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitPush_op(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPush_op(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Push_opContext push_op() {
		Push_opContext _localctx = new Push_opContext(Context, State);
		EnterRule(_localctx, 36, RULE_push_op);
		try {
			State = 231;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 225;
				Match(T__27);
				State = 226;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 227;
				Match(T__27);
				State = 228;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 229;
				Match(T__28);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 230;
				Match(T__29);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pop_opContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		public Pop_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pop_op; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterPop_op(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitPop_op(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPop_op(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pop_opContext pop_op() {
		Pop_opContext _localctx = new Pop_opContext(Context, State);
		EnterRule(_localctx, 38, RULE_pop_op);
		try {
			State = 238;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 233;
				Match(T__30);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 234;
				Match(T__30);
				State = 235;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 236;
				Match(T__31);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 237;
				Match(T__32);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InputContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public InputContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_input; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterInput(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitInput(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInput(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InputContext input() {
		InputContext _localctx = new InputContext(Context, State);
		EnterRule(_localctx, 40, RULE_input);
		try {
			State = 244;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 240;
				Match(T__33);
				State = 241;
				reg();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 242;
				Match(T__33);
				State = 243;
				mem();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrintContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StrContext str() {
			return GetRuleContext<StrContext>(0);
		}
		public PrintContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_print; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterPrint(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitPrint(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrint(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrintContext print() {
		PrintContext _localctx = new PrintContext(Context, State);
		EnterRule(_localctx, 42, RULE_print);
		try {
			State = 263;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,17,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 246;
				Match(T__34);
				State = 247;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 248;
				Match(T__34);
				State = 249;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 250;
				Match(T__34);
				State = 251;
				mem();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 252;
				Match(T__34);
				State = 253;
				str();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 254;
				Match(T__35);
				State = 255;
				num();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 256;
				Match(T__35);
				State = 257;
				reg();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 258;
				Match(T__35);
				State = 259;
				mem();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 260;
				Match(T__35);
				State = 261;
				str();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 262;
				Match(T__35);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public RandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterRand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitRand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RandContext rand() {
		RandContext _localctx = new RandContext(Context, State);
		EnterRule(_localctx, 44, RULE_rand);
		try {
			State = 269;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 265;
				Match(T__36);
				State = 266;
				reg();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 267;
				Match(T__36);
				State = 268;
				mem();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DumpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(toy_asmParser.INT, 0); }
		public DumpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dump; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterDump(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitDump(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDump(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DumpContext dump() {
		DumpContext _localctx = new DumpContext(Context, State);
		EnterRule(_localctx, 46, RULE_dump);
		try {
			State = 277;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 271;
				Match(T__37);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 272;
				Match(T__37);
				State = 273;
				reg();
				State = 274;
				Match(T__12);
				State = 275;
				Match(INT);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PauseContext : ParserRuleContext {
		public PauseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pause; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterPause(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitPause(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPause(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PauseContext pause() {
		PauseContext _localctx = new PauseContext(Context, State);
		EnterRule(_localctx, 48, RULE_pause);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 279;
			Match(T__38);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HaltContext : ParserRuleContext {
		public HaltContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_halt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterHalt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitHalt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHalt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HaltContext halt() {
		HaltContext _localctx = new HaltContext(Context, State);
		EnterRule(_localctx, 50, RULE_halt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 281;
			Match(T__39);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NopContext : ParserRuleContext {
		public NopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nop; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterNop(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitNop(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNop(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NopContext nop() {
		NopContext _localctx = new NopContext(Context, State);
		EnterRule(_localctx, 52, RULE_nop);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 283;
			Match(T__40);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,46,286,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,1,0,1,0,4,0,57,8,0,11,
		0,12,0,58,1,1,3,1,62,8,1,1,1,1,1,1,2,1,2,1,2,1,3,1,3,1,3,1,3,1,3,1,3,1,
		3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,3,3,87,8,3,1,4,3,4,90,8,
		4,1,4,1,4,1,4,3,4,95,8,4,1,5,1,5,1,6,1,6,1,6,1,7,1,7,1,7,3,7,105,8,7,1,
		7,1,7,1,8,1,8,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,
		1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,3,9,136,8,9,1,10,1,10,1,10,
		1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,3,10,153,8,
		10,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,
		11,1,11,3,11,170,8,11,1,12,1,12,1,12,1,12,1,12,1,12,3,12,178,8,12,1,13,
		1,13,1,13,1,13,1,13,1,13,3,13,186,8,13,1,14,1,14,1,14,1,14,1,14,1,14,1,
		14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,3,14,203,8,14,1,15,1,15,1,15,
		1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,3,15,219,8,15,1,
		16,1,16,1,16,1,17,1,17,1,18,1,18,1,18,1,18,1,18,1,18,3,18,232,8,18,1,19,
		1,19,1,19,1,19,1,19,3,19,239,8,19,1,20,1,20,1,20,1,20,3,20,245,8,20,1,
		21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,
		21,1,21,1,21,3,21,264,8,21,1,22,1,22,1,22,1,22,3,22,270,8,22,1,23,1,23,
		1,23,1,23,1,23,1,23,3,23,278,8,23,1,24,1,24,1,25,1,25,1,26,1,26,1,26,0,
		0,27,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,
		48,50,52,0,2,1,0,4,9,1,0,2,3,318,0,56,1,0,0,0,2,61,1,0,0,0,4,65,1,0,0,
		0,6,86,1,0,0,0,8,94,1,0,0,0,10,96,1,0,0,0,12,98,1,0,0,0,14,101,1,0,0,0,
		16,108,1,0,0,0,18,135,1,0,0,0,20,152,1,0,0,0,22,169,1,0,0,0,24,177,1,0,
		0,0,26,185,1,0,0,0,28,202,1,0,0,0,30,218,1,0,0,0,32,220,1,0,0,0,34,223,
		1,0,0,0,36,231,1,0,0,0,38,238,1,0,0,0,40,244,1,0,0,0,42,263,1,0,0,0,44,
		269,1,0,0,0,46,277,1,0,0,0,48,279,1,0,0,0,50,281,1,0,0,0,52,283,1,0,0,
		0,54,57,5,42,0,0,55,57,3,2,1,0,56,54,1,0,0,0,56,55,1,0,0,0,57,58,1,0,0,
		0,58,56,1,0,0,0,58,59,1,0,0,0,59,1,1,0,0,0,60,62,3,4,2,0,61,60,1,0,0,0,
		61,62,1,0,0,0,62,63,1,0,0,0,63,64,3,6,3,0,64,3,1,0,0,0,65,66,5,44,0,0,
		66,67,5,1,0,0,67,5,1,0,0,0,68,87,3,18,9,0,69,87,3,20,10,0,70,87,3,22,11,
		0,71,87,3,24,12,0,72,87,3,26,13,0,73,87,3,28,14,0,74,87,3,30,15,0,75,87,
		3,32,16,0,76,87,3,34,17,0,77,87,3,36,18,0,78,87,3,38,19,0,79,87,3,40,20,
		0,80,87,3,42,21,0,81,87,3,44,22,0,82,87,3,46,23,0,83,87,3,48,24,0,84,87,
		3,50,25,0,85,87,3,52,26,0,86,68,1,0,0,0,86,69,1,0,0,0,86,70,1,0,0,0,86,
		71,1,0,0,0,86,72,1,0,0,0,86,73,1,0,0,0,86,74,1,0,0,0,86,75,1,0,0,0,86,
		76,1,0,0,0,86,77,1,0,0,0,86,78,1,0,0,0,86,79,1,0,0,0,86,80,1,0,0,0,86,
		81,1,0,0,0,86,82,1,0,0,0,86,83,1,0,0,0,86,84,1,0,0,0,86,85,1,0,0,0,87,
		7,1,0,0,0,88,90,5,2,0,0,89,88,1,0,0,0,89,90,1,0,0,0,90,91,1,0,0,0,91,95,
		5,43,0,0,92,93,5,3,0,0,93,95,5,43,0,0,94,89,1,0,0,0,94,92,1,0,0,0,95,9,
		1,0,0,0,96,97,7,0,0,0,97,11,1,0,0,0,98,99,7,1,0,0,99,100,5,43,0,0,100,
		13,1,0,0,0,101,102,5,10,0,0,102,104,3,10,5,0,103,105,3,12,6,0,104,103,
		1,0,0,0,104,105,1,0,0,0,105,106,1,0,0,0,106,107,5,11,0,0,107,15,1,0,0,
		0,108,109,5,45,0,0,109,17,1,0,0,0,110,111,5,12,0,0,111,112,3,10,5,0,112,
		113,5,13,0,0,113,114,3,8,4,0,114,136,1,0,0,0,115,116,5,12,0,0,116,117,
		3,10,5,0,117,118,5,13,0,0,118,119,3,10,5,0,119,136,1,0,0,0,120,121,5,12,
		0,0,121,122,3,10,5,0,122,123,5,13,0,0,123,124,3,14,7,0,124,136,1,0,0,0,
		125,126,5,12,0,0,126,127,3,14,7,0,127,128,5,13,0,0,128,129,3,8,4,0,129,
		136,1,0,0,0,130,131,5,12,0,0,131,132,3,14,7,0,132,133,5,13,0,0,133,134,
		3,10,5,0,134,136,1,0,0,0,135,110,1,0,0,0,135,115,1,0,0,0,135,120,1,0,0,
		0,135,125,1,0,0,0,135,130,1,0,0,0,136,19,1,0,0,0,137,138,5,14,0,0,138,
		139,3,10,5,0,139,140,5,13,0,0,140,141,3,8,4,0,141,153,1,0,0,0,142,143,
		5,14,0,0,143,144,3,10,5,0,144,145,5,13,0,0,145,146,3,10,5,0,146,153,1,
		0,0,0,147,148,5,14,0,0,148,149,3,10,5,0,149,150,5,13,0,0,150,151,3,14,
		7,0,151,153,1,0,0,0,152,137,1,0,0,0,152,142,1,0,0,0,152,147,1,0,0,0,153,
		21,1,0,0,0,154,155,5,15,0,0,155,156,3,10,5,0,156,157,5,13,0,0,157,158,
		3,8,4,0,158,170,1,0,0,0,159,160,5,15,0,0,160,161,3,10,5,0,161,162,5,13,
		0,0,162,163,3,10,5,0,163,170,1,0,0,0,164,165,5,15,0,0,165,166,3,10,5,0,
		166,167,5,13,0,0,167,168,3,14,7,0,168,170,1,0,0,0,169,154,1,0,0,0,169,
		159,1,0,0,0,169,164,1,0,0,0,170,23,1,0,0,0,171,172,5,16,0,0,172,178,3,
		8,4,0,173,174,5,16,0,0,174,178,3,10,5,0,175,176,5,16,0,0,176,178,3,14,
		7,0,177,171,1,0,0,0,177,173,1,0,0,0,177,175,1,0,0,0,178,25,1,0,0,0,179,
		180,5,17,0,0,180,186,3,8,4,0,181,182,5,17,0,0,182,186,3,10,5,0,183,184,
		5,17,0,0,184,186,3,14,7,0,185,179,1,0,0,0,185,181,1,0,0,0,185,183,1,0,
		0,0,186,27,1,0,0,0,187,188,5,18,0,0,188,189,3,10,5,0,189,190,5,13,0,0,
		190,191,3,8,4,0,191,203,1,0,0,0,192,193,5,18,0,0,193,194,3,10,5,0,194,
		195,5,13,0,0,195,196,3,10,5,0,196,203,1,0,0,0,197,198,5,18,0,0,198,199,
		3,10,5,0,199,200,5,13,0,0,200,201,3,14,7,0,201,203,1,0,0,0,202,187,1,0,
		0,0,202,192,1,0,0,0,202,197,1,0,0,0,203,29,1,0,0,0,204,205,5,19,0,0,205,
		219,5,44,0,0,206,207,5,20,0,0,207,219,5,44,0,0,208,209,5,21,0,0,209,219,
		5,44,0,0,210,211,5,22,0,0,211,219,5,44,0,0,212,213,5,23,0,0,213,219,5,
		44,0,0,214,215,5,24,0,0,215,219,5,44,0,0,216,217,5,25,0,0,217,219,5,44,
		0,0,218,204,1,0,0,0,218,206,1,0,0,0,218,208,1,0,0,0,218,210,1,0,0,0,218,
		212,1,0,0,0,218,214,1,0,0,0,218,216,1,0,0,0,219,31,1,0,0,0,220,221,5,26,
		0,0,221,222,5,44,0,0,222,33,1,0,0,0,223,224,5,27,0,0,224,35,1,0,0,0,225,
		226,5,28,0,0,226,232,3,8,4,0,227,228,5,28,0,0,228,232,3,10,5,0,229,232,
		5,29,0,0,230,232,5,30,0,0,231,225,1,0,0,0,231,227,1,0,0,0,231,229,1,0,
		0,0,231,230,1,0,0,0,232,37,1,0,0,0,233,239,5,31,0,0,234,235,5,31,0,0,235,
		239,3,10,5,0,236,239,5,32,0,0,237,239,5,33,0,0,238,233,1,0,0,0,238,234,
		1,0,0,0,238,236,1,0,0,0,238,237,1,0,0,0,239,39,1,0,0,0,240,241,5,34,0,
		0,241,245,3,10,5,0,242,243,5,34,0,0,243,245,3,14,7,0,244,240,1,0,0,0,244,
		242,1,0,0,0,245,41,1,0,0,0,246,247,5,35,0,0,247,264,3,8,4,0,248,249,5,
		35,0,0,249,264,3,10,5,0,250,251,5,35,0,0,251,264,3,14,7,0,252,253,5,35,
		0,0,253,264,3,16,8,0,254,255,5,36,0,0,255,264,3,8,4,0,256,257,5,36,0,0,
		257,264,3,10,5,0,258,259,5,36,0,0,259,264,3,14,7,0,260,261,5,36,0,0,261,
		264,3,16,8,0,262,264,5,36,0,0,263,246,1,0,0,0,263,248,1,0,0,0,263,250,
		1,0,0,0,263,252,1,0,0,0,263,254,1,0,0,0,263,256,1,0,0,0,263,258,1,0,0,
		0,263,260,1,0,0,0,263,262,1,0,0,0,264,43,1,0,0,0,265,266,5,37,0,0,266,
		270,3,10,5,0,267,268,5,37,0,0,268,270,3,14,7,0,269,265,1,0,0,0,269,267,
		1,0,0,0,270,45,1,0,0,0,271,278,5,38,0,0,272,273,5,38,0,0,273,274,3,10,
		5,0,274,275,5,13,0,0,275,276,5,43,0,0,276,278,1,0,0,0,277,271,1,0,0,0,
		277,272,1,0,0,0,278,47,1,0,0,0,279,280,5,39,0,0,280,49,1,0,0,0,281,282,
		5,40,0,0,282,51,1,0,0,0,283,284,5,41,0,0,284,53,1,0,0,0,20,56,58,61,86,
		89,94,104,135,152,169,177,185,202,218,231,238,244,263,269,277
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
