//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from toy_asm.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class toy_asmParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, Comment=41, INT=42, Label=43, STR=44, WS=45;
	public const int
		RULE_program = 0, RULE_opLabel = 1, RULE_op = 2, RULE_num = 3, RULE_reg = 4, 
		RULE_offset = 5, RULE_mem = 6, RULE_str = 7, RULE_move = 8, RULE_add = 9, 
		RULE_sub = 10, RULE_mul = 11, RULE_div = 12, RULE_cmp = 13, RULE_jump = 14, 
		RULE_call = 15, RULE_ret = 16, RULE_push_op = 17, RULE_pop_op = 18, RULE_input = 19, 
		RULE_print = 20, RULE_rand = 21, RULE_dump = 22, RULE_halt = 23, RULE_nop = 24;
	public static readonly string[] ruleNames = {
		"program", "opLabel", "op", "num", "reg", "offset", "mem", "str", "move", 
		"add", "sub", "mul", "div", "cmp", "jump", "call", "ret", "push_op", "pop_op", 
		"input", "print", "rand", "dump", "halt", "nop"
	};

	private static readonly string[] _LiteralNames = {
		null, "':'", "'+'", "'-'", "'ax'", "'bx'", "'cx'", "'dx'", "'bp'", "'sp'", 
		"'['", "']'", "'mov'", "','", "'add'", "'sub'", "'mul'", "'div'", "'cmp'", 
		"'jmp'", "'je'", "'jne'", "'jg'", "'jge'", "'jl'", "'jle'", "'call'", 
		"'ret'", "'push'", "'pushf'", "'pusha'", "'pop'", "'popf'", "'popa'", 
		"'input'", "'print'", "'println'", "'rand'", "'dump'", "'halt'", "'nop'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, "Comment", "INT", "Label", "STR", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "toy_asm.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static toy_asmParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public toy_asmParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public toy_asmParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(toy_asmParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comment() { return GetTokens(toy_asmParser.Comment); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comment(int i) {
			return GetToken(toy_asmParser.Comment, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpContext[] op() {
			return GetRuleContexts<OpContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpContext op(int i) {
			return GetRuleContext<OpContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpLabelContext[] opLabel() {
			return GetRuleContexts<OpLabelContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpLabelContext opLabel(int i) {
			return GetRuleContext<OpLabelContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 55;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					State = 53;
					ErrorHandler.Sync(this);
					switch (TokenStream.LA(1)) {
					case Comment:
						{
						State = 50;
						Match(Comment);
						}
						break;
					case Label:
						{
						State = 51;
						opLabel();
						}
						break;
					case T__11:
					case T__13:
					case T__14:
					case T__15:
					case T__16:
					case T__17:
					case T__18:
					case T__19:
					case T__20:
					case T__21:
					case T__22:
					case T__23:
					case T__24:
					case T__25:
					case T__26:
					case T__27:
					case T__28:
					case T__29:
					case T__30:
					case T__31:
					case T__32:
					case T__33:
					case T__34:
					case T__35:
					case T__36:
					case T__37:
					case T__38:
					case T__39:
						{
						State = 52;
						op();
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					} 
				}
				State = 57;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			}
			State = 60;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Comment:
				{
				State = 58;
				Match(Comment);
				}
				break;
			case T__11:
			case T__13:
			case T__14:
			case T__15:
			case T__16:
			case T__17:
			case T__18:
			case T__19:
			case T__20:
			case T__21:
			case T__22:
			case T__23:
			case T__24:
			case T__25:
			case T__26:
			case T__27:
			case T__28:
			case T__29:
			case T__30:
			case T__31:
			case T__32:
			case T__33:
			case T__34:
			case T__35:
			case T__36:
			case T__37:
			case T__38:
			case T__39:
				{
				State = 59;
				op();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 62;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OpLabelContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Label() { return GetToken(toy_asmParser.Label, 0); }
		public OpLabelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_opLabel; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterOpLabel(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitOpLabel(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOpLabel(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OpLabelContext opLabel() {
		OpLabelContext _localctx = new OpLabelContext(Context, State);
		EnterRule(_localctx, 2, RULE_opLabel);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 64;
			Match(Label);
			State = 65;
			Match(T__0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MoveContext move() {
			return GetRuleContext<MoveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AddContext add() {
			return GetRuleContext<AddContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SubContext sub() {
			return GetRuleContext<SubContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MulContext mul() {
			return GetRuleContext<MulContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DivContext div() {
			return GetRuleContext<DivContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CmpContext cmp() {
			return GetRuleContext<CmpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public JumpContext jump() {
			return GetRuleContext<JumpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CallContext call() {
			return GetRuleContext<CallContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RetContext ret() {
			return GetRuleContext<RetContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Push_opContext push_op() {
			return GetRuleContext<Push_opContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pop_opContext pop_op() {
			return GetRuleContext<Pop_opContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InputContext input() {
			return GetRuleContext<InputContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrintContext print() {
			return GetRuleContext<PrintContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RandContext rand() {
			return GetRuleContext<RandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DumpContext dump() {
			return GetRuleContext<DumpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public HaltContext halt() {
			return GetRuleContext<HaltContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NopContext nop() {
			return GetRuleContext<NopContext>(0);
		}
		public OpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_op; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OpContext op() {
		OpContext _localctx = new OpContext(Context, State);
		EnterRule(_localctx, 4, RULE_op);
		try {
			State = 84;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__11:
				EnterOuterAlt(_localctx, 1);
				{
				State = 67;
				move();
				}
				break;
			case T__13:
				EnterOuterAlt(_localctx, 2);
				{
				State = 68;
				add();
				}
				break;
			case T__14:
				EnterOuterAlt(_localctx, 3);
				{
				State = 69;
				sub();
				}
				break;
			case T__15:
				EnterOuterAlt(_localctx, 4);
				{
				State = 70;
				mul();
				}
				break;
			case T__16:
				EnterOuterAlt(_localctx, 5);
				{
				State = 71;
				div();
				}
				break;
			case T__17:
				EnterOuterAlt(_localctx, 6);
				{
				State = 72;
				cmp();
				}
				break;
			case T__18:
			case T__19:
			case T__20:
			case T__21:
			case T__22:
			case T__23:
			case T__24:
				EnterOuterAlt(_localctx, 7);
				{
				State = 73;
				jump();
				}
				break;
			case T__25:
				EnterOuterAlt(_localctx, 8);
				{
				State = 74;
				call();
				}
				break;
			case T__26:
				EnterOuterAlt(_localctx, 9);
				{
				State = 75;
				ret();
				}
				break;
			case T__27:
			case T__28:
			case T__29:
				EnterOuterAlt(_localctx, 10);
				{
				State = 76;
				push_op();
				}
				break;
			case T__30:
			case T__31:
			case T__32:
				EnterOuterAlt(_localctx, 11);
				{
				State = 77;
				pop_op();
				}
				break;
			case T__33:
				EnterOuterAlt(_localctx, 12);
				{
				State = 78;
				input();
				}
				break;
			case T__34:
			case T__35:
				EnterOuterAlt(_localctx, 13);
				{
				State = 79;
				print();
				}
				break;
			case T__36:
				EnterOuterAlt(_localctx, 14);
				{
				State = 80;
				rand();
				}
				break;
			case T__37:
				EnterOuterAlt(_localctx, 15);
				{
				State = 81;
				dump();
				}
				break;
			case T__38:
				EnterOuterAlt(_localctx, 16);
				{
				State = 82;
				halt();
				}
				break;
			case T__39:
				EnterOuterAlt(_localctx, 17);
				{
				State = 83;
				nop();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(toy_asmParser.INT, 0); }
		public NumContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_num; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterNum(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitNum(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNum(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumContext num() {
		NumContext _localctx = new NumContext(Context, State);
		EnterRule(_localctx, 6, RULE_num);
		int _la;
		try {
			State = 92;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__1:
			case INT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 87;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__1) {
					{
					State = 86;
					Match(T__1);
					}
				}

				State = 89;
				Match(INT);
				}
				break;
			case T__2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 90;
				Match(T__2);
				State = 91;
				Match(INT);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RegContext : ParserRuleContext {
		public RegContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_reg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterReg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitReg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RegContext reg() {
		RegContext _localctx = new RegContext(Context, State);
		EnterRule(_localctx, 8, RULE_reg);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 94;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 1008L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OffsetContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(toy_asmParser.INT, 0); }
		public OffsetContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_offset; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterOffset(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitOffset(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOffset(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OffsetContext offset() {
		OffsetContext _localctx = new OffsetContext(Context, State);
		EnterRule(_localctx, 10, RULE_offset);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96;
			_la = TokenStream.LA(1);
			if ( !(_la==T__1 || _la==T__2) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 97;
			Match(INT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MemContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OffsetContext offset() {
			return GetRuleContext<OffsetContext>(0);
		}
		public MemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mem; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterMem(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitMem(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMem(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MemContext mem() {
		MemContext _localctx = new MemContext(Context, State);
		EnterRule(_localctx, 12, RULE_mem);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 99;
			Match(T__9);
			State = 100;
			reg();
			State = 102;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__1 || _la==T__2) {
				{
				State = 101;
				offset();
				}
			}

			State = 104;
			Match(T__10);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StrContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STR() { return GetToken(toy_asmParser.STR, 0); }
		public StrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_str; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterStr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitStr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StrContext str() {
		StrContext _localctx = new StrContext(Context, State);
		EnterRule(_localctx, 14, RULE_str);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 106;
			Match(STR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MoveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext[] reg() {
			return GetRuleContexts<RegContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg(int i) {
			return GetRuleContext<RegContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public MoveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_move; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterMove(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitMove(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMove(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MoveContext move() {
		MoveContext _localctx = new MoveContext(Context, State);
		EnterRule(_localctx, 16, RULE_move);
		try {
			State = 133;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 108;
				Match(T__11);
				State = 109;
				reg();
				State = 110;
				Match(T__12);
				State = 111;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 113;
				Match(T__11);
				State = 114;
				reg();
				State = 115;
				Match(T__12);
				State = 116;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 118;
				Match(T__11);
				State = 119;
				reg();
				State = 120;
				Match(T__12);
				State = 121;
				mem();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 123;
				Match(T__11);
				State = 124;
				mem();
				State = 125;
				Match(T__12);
				State = 126;
				num();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 128;
				Match(T__11);
				State = 129;
				mem();
				State = 130;
				Match(T__12);
				State = 131;
				reg();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AddContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext[] reg() {
			return GetRuleContexts<RegContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg(int i) {
			return GetRuleContext<RegContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public AddContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_add; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterAdd(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitAdd(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAdd(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AddContext add() {
		AddContext _localctx = new AddContext(Context, State);
		EnterRule(_localctx, 18, RULE_add);
		try {
			State = 150;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 135;
				Match(T__13);
				State = 136;
				reg();
				State = 137;
				Match(T__12);
				State = 138;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 140;
				Match(T__13);
				State = 141;
				reg();
				State = 142;
				Match(T__12);
				State = 143;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 145;
				Match(T__13);
				State = 146;
				reg();
				State = 147;
				Match(T__12);
				State = 148;
				mem();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SubContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext[] reg() {
			return GetRuleContexts<RegContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg(int i) {
			return GetRuleContext<RegContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public SubContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sub; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterSub(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitSub(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSub(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SubContext sub() {
		SubContext _localctx = new SubContext(Context, State);
		EnterRule(_localctx, 20, RULE_sub);
		try {
			State = 167;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 152;
				Match(T__14);
				State = 153;
				reg();
				State = 154;
				Match(T__12);
				State = 155;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 157;
				Match(T__14);
				State = 158;
				reg();
				State = 159;
				Match(T__12);
				State = 160;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 162;
				Match(T__14);
				State = 163;
				reg();
				State = 164;
				Match(T__12);
				State = 165;
				mem();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MulContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public MulContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mul; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterMul(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitMul(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMul(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MulContext mul() {
		MulContext _localctx = new MulContext(Context, State);
		EnterRule(_localctx, 22, RULE_mul);
		try {
			State = 175;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 169;
				Match(T__15);
				State = 170;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 171;
				Match(T__15);
				State = 172;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 173;
				Match(T__15);
				State = 174;
				mem();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DivContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public DivContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_div; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterDiv(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitDiv(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDiv(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DivContext div() {
		DivContext _localctx = new DivContext(Context, State);
		EnterRule(_localctx, 24, RULE_div);
		try {
			State = 183;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 177;
				Match(T__16);
				State = 178;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 179;
				Match(T__16);
				State = 180;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 181;
				Match(T__16);
				State = 182;
				mem();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CmpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext[] reg() {
			return GetRuleContexts<RegContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg(int i) {
			return GetRuleContext<RegContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public CmpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cmp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterCmp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitCmp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCmp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CmpContext cmp() {
		CmpContext _localctx = new CmpContext(Context, State);
		EnterRule(_localctx, 26, RULE_cmp);
		try {
			State = 200;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 185;
				Match(T__17);
				State = 186;
				reg();
				State = 187;
				Match(T__12);
				State = 188;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 190;
				Match(T__17);
				State = 191;
				reg();
				State = 192;
				Match(T__12);
				State = 193;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 195;
				Match(T__17);
				State = 196;
				reg();
				State = 197;
				Match(T__12);
				State = 198;
				mem();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JumpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Label() { return GetToken(toy_asmParser.Label, 0); }
		public JumpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jump; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterJump(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitJump(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJump(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JumpContext jump() {
		JumpContext _localctx = new JumpContext(Context, State);
		EnterRule(_localctx, 28, RULE_jump);
		try {
			State = 216;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__18:
				EnterOuterAlt(_localctx, 1);
				{
				State = 202;
				Match(T__18);
				State = 203;
				Match(Label);
				}
				break;
			case T__19:
				EnterOuterAlt(_localctx, 2);
				{
				State = 204;
				Match(T__19);
				State = 205;
				Match(Label);
				}
				break;
			case T__20:
				EnterOuterAlt(_localctx, 3);
				{
				State = 206;
				Match(T__20);
				State = 207;
				Match(Label);
				}
				break;
			case T__21:
				EnterOuterAlt(_localctx, 4);
				{
				State = 208;
				Match(T__21);
				State = 209;
				Match(Label);
				}
				break;
			case T__22:
				EnterOuterAlt(_localctx, 5);
				{
				State = 210;
				Match(T__22);
				State = 211;
				Match(Label);
				}
				break;
			case T__23:
				EnterOuterAlt(_localctx, 6);
				{
				State = 212;
				Match(T__23);
				State = 213;
				Match(Label);
				}
				break;
			case T__24:
				EnterOuterAlt(_localctx, 7);
				{
				State = 214;
				Match(T__24);
				State = 215;
				Match(Label);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CallContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Label() { return GetToken(toy_asmParser.Label, 0); }
		public CallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_call; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CallContext call() {
		CallContext _localctx = new CallContext(Context, State);
		EnterRule(_localctx, 30, RULE_call);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 218;
			Match(T__25);
			State = 219;
			Match(Label);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RetContext : ParserRuleContext {
		public RetContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ret; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterRet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitRet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRet(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RetContext ret() {
		RetContext _localctx = new RetContext(Context, State);
		EnterRule(_localctx, 32, RULE_ret);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 221;
			Match(T__26);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Push_opContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		public Push_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_push_op; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterPush_op(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitPush_op(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPush_op(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Push_opContext push_op() {
		Push_opContext _localctx = new Push_opContext(Context, State);
		EnterRule(_localctx, 34, RULE_push_op);
		try {
			State = 229;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 223;
				Match(T__27);
				State = 224;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 225;
				Match(T__27);
				State = 226;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 227;
				Match(T__28);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 228;
				Match(T__29);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pop_opContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		public Pop_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pop_op; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterPop_op(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitPop_op(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPop_op(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pop_opContext pop_op() {
		Pop_opContext _localctx = new Pop_opContext(Context, State);
		EnterRule(_localctx, 36, RULE_pop_op);
		try {
			State = 236;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 231;
				Match(T__30);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 232;
				Match(T__30);
				State = 233;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 234;
				Match(T__31);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 235;
				Match(T__32);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InputContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public InputContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_input; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterInput(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitInput(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInput(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InputContext input() {
		InputContext _localctx = new InputContext(Context, State);
		EnterRule(_localctx, 38, RULE_input);
		try {
			State = 242;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 238;
				Match(T__33);
				State = 239;
				reg();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 240;
				Match(T__33);
				State = 241;
				mem();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrintContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StrContext str() {
			return GetRuleContext<StrContext>(0);
		}
		public PrintContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_print; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterPrint(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitPrint(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrint(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrintContext print() {
		PrintContext _localctx = new PrintContext(Context, State);
		EnterRule(_localctx, 40, RULE_print);
		try {
			State = 261;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,17,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 244;
				Match(T__34);
				State = 245;
				num();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 246;
				Match(T__34);
				State = 247;
				reg();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 248;
				Match(T__34);
				State = 249;
				mem();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 250;
				Match(T__34);
				State = 251;
				str();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 252;
				Match(T__35);
				State = 253;
				num();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 254;
				Match(T__35);
				State = 255;
				reg();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 256;
				Match(T__35);
				State = 257;
				mem();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 258;
				Match(T__35);
				State = 259;
				str();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 260;
				Match(T__35);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemContext mem() {
			return GetRuleContext<MemContext>(0);
		}
		public RandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterRand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitRand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RandContext rand() {
		RandContext _localctx = new RandContext(Context, State);
		EnterRule(_localctx, 42, RULE_rand);
		try {
			State = 267;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 263;
				Match(T__36);
				State = 264;
				reg();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 265;
				Match(T__36);
				State = 266;
				mem();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DumpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegContext reg() {
			return GetRuleContext<RegContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(toy_asmParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		public DumpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dump; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterDump(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitDump(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDump(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DumpContext dump() {
		DumpContext _localctx = new DumpContext(Context, State);
		EnterRule(_localctx, 44, RULE_dump);
		try {
			State = 280;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 269;
				Match(T__37);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 270;
				Match(T__37);
				State = 271;
				reg();
				State = 272;
				Match(T__12);
				State = 273;
				Match(INT);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 275;
				Match(T__37);
				State = 276;
				num();
				State = 277;
				Match(T__12);
				State = 278;
				Match(INT);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HaltContext : ParserRuleContext {
		public HaltContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_halt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterHalt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitHalt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHalt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HaltContext halt() {
		HaltContext _localctx = new HaltContext(Context, State);
		EnterRule(_localctx, 46, RULE_halt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 282;
			Match(T__38);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NopContext : ParserRuleContext {
		public NopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nop; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.EnterNop(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			Itoy_asmListener typedListener = listener as Itoy_asmListener;
			if (typedListener != null) typedListener.ExitNop(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			Itoy_asmVisitor<TResult> typedVisitor = visitor as Itoy_asmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNop(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NopContext nop() {
		NopContext _localctx = new NopContext(Context, State);
		EnterRule(_localctx, 48, RULE_nop);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 284;
			Match(T__39);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,45,287,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,1,0,1,0,1,0,5,0,54,8,0,10,0,12,0,57,9,0,
		1,0,1,0,3,0,61,8,0,1,0,1,0,1,1,1,1,1,1,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,
		1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,3,2,85,8,2,1,3,3,3,88,8,3,1,3,1,3,
		1,3,3,3,93,8,3,1,4,1,4,1,5,1,5,1,5,1,6,1,6,1,6,3,6,103,8,6,1,6,1,6,1,7,
		1,7,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,
		8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,3,8,134,8,8,1,9,1,9,1,9,1,9,1,9,1,9,
		1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,3,9,151,8,9,1,10,1,10,1,10,1,10,1,
		10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,3,10,168,8,10,1,11,
		1,11,1,11,1,11,1,11,1,11,3,11,176,8,11,1,12,1,12,1,12,1,12,1,12,1,12,3,
		12,184,8,12,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,
		1,13,1,13,1,13,3,13,201,8,13,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,
		14,1,14,1,14,1,14,1,14,1,14,3,14,217,8,14,1,15,1,15,1,15,1,16,1,16,1,17,
		1,17,1,17,1,17,1,17,1,17,3,17,230,8,17,1,18,1,18,1,18,1,18,1,18,3,18,237,
		8,18,1,19,1,19,1,19,1,19,3,19,243,8,19,1,20,1,20,1,20,1,20,1,20,1,20,1,
		20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,3,20,262,8,20,1,21,
		1,21,1,21,1,21,3,21,268,8,21,1,22,1,22,1,22,1,22,1,22,1,22,1,22,1,22,1,
		22,1,22,1,22,3,22,281,8,22,1,23,1,23,1,24,1,24,1,24,0,0,25,0,2,4,6,8,10,
		12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,0,2,1,0,4,9,1,
		0,2,3,322,0,55,1,0,0,0,2,64,1,0,0,0,4,84,1,0,0,0,6,92,1,0,0,0,8,94,1,0,
		0,0,10,96,1,0,0,0,12,99,1,0,0,0,14,106,1,0,0,0,16,133,1,0,0,0,18,150,1,
		0,0,0,20,167,1,0,0,0,22,175,1,0,0,0,24,183,1,0,0,0,26,200,1,0,0,0,28,216,
		1,0,0,0,30,218,1,0,0,0,32,221,1,0,0,0,34,229,1,0,0,0,36,236,1,0,0,0,38,
		242,1,0,0,0,40,261,1,0,0,0,42,267,1,0,0,0,44,280,1,0,0,0,46,282,1,0,0,
		0,48,284,1,0,0,0,50,54,5,41,0,0,51,54,3,2,1,0,52,54,3,4,2,0,53,50,1,0,
		0,0,53,51,1,0,0,0,53,52,1,0,0,0,54,57,1,0,0,0,55,53,1,0,0,0,55,56,1,0,
		0,0,56,60,1,0,0,0,57,55,1,0,0,0,58,61,5,41,0,0,59,61,3,4,2,0,60,58,1,0,
		0,0,60,59,1,0,0,0,61,62,1,0,0,0,62,63,5,0,0,1,63,1,1,0,0,0,64,65,5,43,
		0,0,65,66,5,1,0,0,66,3,1,0,0,0,67,85,3,16,8,0,68,85,3,18,9,0,69,85,3,20,
		10,0,70,85,3,22,11,0,71,85,3,24,12,0,72,85,3,26,13,0,73,85,3,28,14,0,74,
		85,3,30,15,0,75,85,3,32,16,0,76,85,3,34,17,0,77,85,3,36,18,0,78,85,3,38,
		19,0,79,85,3,40,20,0,80,85,3,42,21,0,81,85,3,44,22,0,82,85,3,46,23,0,83,
		85,3,48,24,0,84,67,1,0,0,0,84,68,1,0,0,0,84,69,1,0,0,0,84,70,1,0,0,0,84,
		71,1,0,0,0,84,72,1,0,0,0,84,73,1,0,0,0,84,74,1,0,0,0,84,75,1,0,0,0,84,
		76,1,0,0,0,84,77,1,0,0,0,84,78,1,0,0,0,84,79,1,0,0,0,84,80,1,0,0,0,84,
		81,1,0,0,0,84,82,1,0,0,0,84,83,1,0,0,0,85,5,1,0,0,0,86,88,5,2,0,0,87,86,
		1,0,0,0,87,88,1,0,0,0,88,89,1,0,0,0,89,93,5,42,0,0,90,91,5,3,0,0,91,93,
		5,42,0,0,92,87,1,0,0,0,92,90,1,0,0,0,93,7,1,0,0,0,94,95,7,0,0,0,95,9,1,
		0,0,0,96,97,7,1,0,0,97,98,5,42,0,0,98,11,1,0,0,0,99,100,5,10,0,0,100,102,
		3,8,4,0,101,103,3,10,5,0,102,101,1,0,0,0,102,103,1,0,0,0,103,104,1,0,0,
		0,104,105,5,11,0,0,105,13,1,0,0,0,106,107,5,44,0,0,107,15,1,0,0,0,108,
		109,5,12,0,0,109,110,3,8,4,0,110,111,5,13,0,0,111,112,3,6,3,0,112,134,
		1,0,0,0,113,114,5,12,0,0,114,115,3,8,4,0,115,116,5,13,0,0,116,117,3,8,
		4,0,117,134,1,0,0,0,118,119,5,12,0,0,119,120,3,8,4,0,120,121,5,13,0,0,
		121,122,3,12,6,0,122,134,1,0,0,0,123,124,5,12,0,0,124,125,3,12,6,0,125,
		126,5,13,0,0,126,127,3,6,3,0,127,134,1,0,0,0,128,129,5,12,0,0,129,130,
		3,12,6,0,130,131,5,13,0,0,131,132,3,8,4,0,132,134,1,0,0,0,133,108,1,0,
		0,0,133,113,1,0,0,0,133,118,1,0,0,0,133,123,1,0,0,0,133,128,1,0,0,0,134,
		17,1,0,0,0,135,136,5,14,0,0,136,137,3,8,4,0,137,138,5,13,0,0,138,139,3,
		6,3,0,139,151,1,0,0,0,140,141,5,14,0,0,141,142,3,8,4,0,142,143,5,13,0,
		0,143,144,3,8,4,0,144,151,1,0,0,0,145,146,5,14,0,0,146,147,3,8,4,0,147,
		148,5,13,0,0,148,149,3,12,6,0,149,151,1,0,0,0,150,135,1,0,0,0,150,140,
		1,0,0,0,150,145,1,0,0,0,151,19,1,0,0,0,152,153,5,15,0,0,153,154,3,8,4,
		0,154,155,5,13,0,0,155,156,3,6,3,0,156,168,1,0,0,0,157,158,5,15,0,0,158,
		159,3,8,4,0,159,160,5,13,0,0,160,161,3,8,4,0,161,168,1,0,0,0,162,163,5,
		15,0,0,163,164,3,8,4,0,164,165,5,13,0,0,165,166,3,12,6,0,166,168,1,0,0,
		0,167,152,1,0,0,0,167,157,1,0,0,0,167,162,1,0,0,0,168,21,1,0,0,0,169,170,
		5,16,0,0,170,176,3,6,3,0,171,172,5,16,0,0,172,176,3,8,4,0,173,174,5,16,
		0,0,174,176,3,12,6,0,175,169,1,0,0,0,175,171,1,0,0,0,175,173,1,0,0,0,176,
		23,1,0,0,0,177,178,5,17,0,0,178,184,3,6,3,0,179,180,5,17,0,0,180,184,3,
		8,4,0,181,182,5,17,0,0,182,184,3,12,6,0,183,177,1,0,0,0,183,179,1,0,0,
		0,183,181,1,0,0,0,184,25,1,0,0,0,185,186,5,18,0,0,186,187,3,8,4,0,187,
		188,5,13,0,0,188,189,3,6,3,0,189,201,1,0,0,0,190,191,5,18,0,0,191,192,
		3,8,4,0,192,193,5,13,0,0,193,194,3,8,4,0,194,201,1,0,0,0,195,196,5,18,
		0,0,196,197,3,8,4,0,197,198,5,13,0,0,198,199,3,12,6,0,199,201,1,0,0,0,
		200,185,1,0,0,0,200,190,1,0,0,0,200,195,1,0,0,0,201,27,1,0,0,0,202,203,
		5,19,0,0,203,217,5,43,0,0,204,205,5,20,0,0,205,217,5,43,0,0,206,207,5,
		21,0,0,207,217,5,43,0,0,208,209,5,22,0,0,209,217,5,43,0,0,210,211,5,23,
		0,0,211,217,5,43,0,0,212,213,5,24,0,0,213,217,5,43,0,0,214,215,5,25,0,
		0,215,217,5,43,0,0,216,202,1,0,0,0,216,204,1,0,0,0,216,206,1,0,0,0,216,
		208,1,0,0,0,216,210,1,0,0,0,216,212,1,0,0,0,216,214,1,0,0,0,217,29,1,0,
		0,0,218,219,5,26,0,0,219,220,5,43,0,0,220,31,1,0,0,0,221,222,5,27,0,0,
		222,33,1,0,0,0,223,224,5,28,0,0,224,230,3,6,3,0,225,226,5,28,0,0,226,230,
		3,8,4,0,227,230,5,29,0,0,228,230,5,30,0,0,229,223,1,0,0,0,229,225,1,0,
		0,0,229,227,1,0,0,0,229,228,1,0,0,0,230,35,1,0,0,0,231,237,5,31,0,0,232,
		233,5,31,0,0,233,237,3,8,4,0,234,237,5,32,0,0,235,237,5,33,0,0,236,231,
		1,0,0,0,236,232,1,0,0,0,236,234,1,0,0,0,236,235,1,0,0,0,237,37,1,0,0,0,
		238,239,5,34,0,0,239,243,3,8,4,0,240,241,5,34,0,0,241,243,3,12,6,0,242,
		238,1,0,0,0,242,240,1,0,0,0,243,39,1,0,0,0,244,245,5,35,0,0,245,262,3,
		6,3,0,246,247,5,35,0,0,247,262,3,8,4,0,248,249,5,35,0,0,249,262,3,12,6,
		0,250,251,5,35,0,0,251,262,3,14,7,0,252,253,5,36,0,0,253,262,3,6,3,0,254,
		255,5,36,0,0,255,262,3,8,4,0,256,257,5,36,0,0,257,262,3,12,6,0,258,259,
		5,36,0,0,259,262,3,14,7,0,260,262,5,36,0,0,261,244,1,0,0,0,261,246,1,0,
		0,0,261,248,1,0,0,0,261,250,1,0,0,0,261,252,1,0,0,0,261,254,1,0,0,0,261,
		256,1,0,0,0,261,258,1,0,0,0,261,260,1,0,0,0,262,41,1,0,0,0,263,264,5,37,
		0,0,264,268,3,8,4,0,265,266,5,37,0,0,266,268,3,12,6,0,267,263,1,0,0,0,
		267,265,1,0,0,0,268,43,1,0,0,0,269,281,5,38,0,0,270,271,5,38,0,0,271,272,
		3,8,4,0,272,273,5,13,0,0,273,274,5,42,0,0,274,281,1,0,0,0,275,276,5,38,
		0,0,276,277,3,6,3,0,277,278,5,13,0,0,278,279,5,42,0,0,279,281,1,0,0,0,
		280,269,1,0,0,0,280,270,1,0,0,0,280,275,1,0,0,0,281,45,1,0,0,0,282,283,
		5,39,0,0,283,47,1,0,0,0,284,285,5,40,0,0,285,49,1,0,0,0,20,53,55,60,84,
		87,92,102,133,150,167,175,183,200,216,229,236,242,261,267,280
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
