//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from toy_asm.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="toy_asmParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface Itoy_asmVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] toy_asmParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.opWithLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpWithLabel([NotNull] toy_asmParser.OpWithLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.opLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpLabel([NotNull] toy_asmParser.OpLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp([NotNull] toy_asmParser.OpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum([NotNull] toy_asmParser.NumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.reg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReg([NotNull] toy_asmParser.RegContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.offset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOffset([NotNull] toy_asmParser.OffsetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.mem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMem([NotNull] toy_asmParser.MemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStr([NotNull] toy_asmParser.StrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.move"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMove([NotNull] toy_asmParser.MoveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdd([NotNull] toy_asmParser.AddContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.sub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSub([NotNull] toy_asmParser.SubContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.mul"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMul([NotNull] toy_asmParser.MulContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.div"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiv([NotNull] toy_asmParser.DivContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.cmp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCmp([NotNull] toy_asmParser.CmpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.jump"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJump([NotNull] toy_asmParser.JumpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall([NotNull] toy_asmParser.CallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.ret"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRet([NotNull] toy_asmParser.RetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.push_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPush_op([NotNull] toy_asmParser.Push_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.pop_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPop_op([NotNull] toy_asmParser.Pop_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput([NotNull] toy_asmParser.InputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint([NotNull] toy_asmParser.PrintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.rand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRand([NotNull] toy_asmParser.RandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.dump"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDump([NotNull] toy_asmParser.DumpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.halt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHalt([NotNull] toy_asmParser.HaltContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="toy_asmParser.nop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNop([NotNull] toy_asmParser.NopContext context);
}
