//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from toy_asm.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="Itoy_asmListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class toy_asmBaseListener : Itoy_asmListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] toy_asmParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] toy_asmParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.opWithLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpWithLabel([NotNull] toy_asmParser.OpWithLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.opWithLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpWithLabel([NotNull] toy_asmParser.OpWithLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.opLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLabel([NotNull] toy_asmParser.OpLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.opLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLabel([NotNull] toy_asmParser.OpLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp([NotNull] toy_asmParser.OpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp([NotNull] toy_asmParser.OpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.num"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNum([NotNull] toy_asmParser.NumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.num"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNum([NotNull] toy_asmParser.NumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.reg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReg([NotNull] toy_asmParser.RegContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.reg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReg([NotNull] toy_asmParser.RegContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.offset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOffset([NotNull] toy_asmParser.OffsetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.offset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOffset([NotNull] toy_asmParser.OffsetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.mem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMem([NotNull] toy_asmParser.MemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.mem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMem([NotNull] toy_asmParser.MemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStr([NotNull] toy_asmParser.StrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStr([NotNull] toy_asmParser.StrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.move"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMove([NotNull] toy_asmParser.MoveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.move"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMove([NotNull] toy_asmParser.MoveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.add"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd([NotNull] toy_asmParser.AddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.add"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd([NotNull] toy_asmParser.AddContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.sub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSub([NotNull] toy_asmParser.SubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.sub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSub([NotNull] toy_asmParser.SubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.mul"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMul([NotNull] toy_asmParser.MulContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.mul"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMul([NotNull] toy_asmParser.MulContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.div"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiv([NotNull] toy_asmParser.DivContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.div"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiv([NotNull] toy_asmParser.DivContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.cmp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmp([NotNull] toy_asmParser.CmpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.cmp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmp([NotNull] toy_asmParser.CmpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.jump"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJump([NotNull] toy_asmParser.JumpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.jump"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJump([NotNull] toy_asmParser.JumpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] toy_asmParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] toy_asmParser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.ret"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRet([NotNull] toy_asmParser.RetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.ret"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRet([NotNull] toy_asmParser.RetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.push_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPush_op([NotNull] toy_asmParser.Push_opContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.push_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPush_op([NotNull] toy_asmParser.Push_opContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.pop_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPop_op([NotNull] toy_asmParser.Pop_opContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.pop_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPop_op([NotNull] toy_asmParser.Pop_opContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput([NotNull] toy_asmParser.InputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput([NotNull] toy_asmParser.InputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint([NotNull] toy_asmParser.PrintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint([NotNull] toy_asmParser.PrintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.rand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRand([NotNull] toy_asmParser.RandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.rand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRand([NotNull] toy_asmParser.RandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.dump"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDump([NotNull] toy_asmParser.DumpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.dump"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDump([NotNull] toy_asmParser.DumpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.halt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHalt([NotNull] toy_asmParser.HaltContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.halt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHalt([NotNull] toy_asmParser.HaltContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="toy_asmParser.nop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNop([NotNull] toy_asmParser.NopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="toy_asmParser.nop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNop([NotNull] toy_asmParser.NopContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
